### ISSUE TITLE
Tuples in Readme

### ISSUE THREAD

**Issue by AlexMouton** [rgrempel/purescript-elm#17]
Hi R
Watching a video of yours just now and its excellent!
Looking at the docs to follow along, i notice your statements about Tuple not having a literal syntax.
I was wondering if you had considered the infix (/\) ? Its more elaborate than a comma for sure, but does work largely the same.

Thanks
Alex

**Comment by rgrempel** [comment]
Ah, in fact, Purescript now has a `(/\)` operator for constructing tuples, both at the type level and the value level. So, I should mention that in the README.

**Comment by AlexMouton** [comment]
oh, thats what I meant to type.  looks like the \\ got eaten

**Comment by rgrempel** [comment]
I've moved that explanatory material over to [purescript-pselm-core](https://github.com/pselm/core) after a bit of a reorganization, and I added the reference to `(/\)` ... thanks!
