### ISSUE TITLE
Speak at Unscripted

### ISSUE THREAD

**Issue by texastoland** [rgrempel/purescript-elm#5]
@paf31 asked me if you might be interested in presenting this at one of our remote Unscripted meetups? I'd also very much like it if you could be on [April 9](http://meetu.ps/2W8s9M) with @alexmingoia who implemented Elm's architecture in [Pux](https://github.com/alexmingoia/purescript-pux/issues)!

**Comment by rgrempel** [comment]
Sure, I'd be happy to do that. Though it is very much a work-in-progress at this point -- I don't have the kind of interesting demo that I hope to have later on. But I can probably think of something to say.
