### ISSUE TITLE
Look at purescript-drawing for implementing Elm.Graphics.Collage

### ISSUE THREAD

**Issue by rgrempel** [rgrempel/purescript-elm#6]
For some reason, I overlooked [purescript-drawing](https://pursuit.purescript.org/packages/purescript-drawing) when I started work on Elm.Graphics.Collage.

I'm far enough along that I probably shouldn't stop now. But, once I'm done, I should take a look at re-implementing at least parts of Elm.Graphics.Collage by relying on purescript-drawing. (Which may or may not turn out to be feasible).

**Comment by rgrempel** [comment]
I also overlooked [purescript-free-canvas](https://github.com/paf31/purescript-free-canvas) ... should check that out as well.

**Comment by paf31** [comment]
`free-canvas` is probably quite slow by comparison. And maybe out of date.
